module ApplicationHelper
  CAPTIONS = ["This caption isn't funny.",
              "I'm hungry for cookies.",
              "Future heart breaker",
              "Thug lyfe",
              "Are you as bored as I am?",
              "Who do you think you are?",
              "Friends for life.",
              "Never met a mirror that I didn't like.",
              "Don't worry, I can handle this.",
              "I don't get most jokes, but I laugh anyways.",
              "#WINNING",
              "Don't worry, I know what I'm doing.",
              "Only you know what is on my mind.",
              "I'm your brother.",
              "All the single ladies",
              "Hey I just met you, and this is crazy...",
              "It's hard being this beautiful.",
              "Reall ridiculously good looking.",
              "Does this make my butt look big?",
              "Life is short.  Eat dessert before dinner.",
              "This is how my last hospital visit began...",
              "I prefer large posteriors and I cannot fib.",
              "I'm not a hipster.",
              "My diet starts tomorrow."]
end
